spring.application.name=reparto-router-web
# Conexión a MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/reparto_router_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Root1990.

# Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Puerto del servidor (opcional, 8080 es el default)
server.port=8080